# -*- coding: utf-8 -*-
"""LeetCode_python_Longest_Common_Prefix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PlLvJQ51WiaqrviwsgZkxJCvcD-KKtt4
"""

class Solution:
    def longestCommonPrefix(self, strs: List[str]) -> str:
        if (len(strs) == 0 ):
            return "Empty list"
        else:
            shortest_str = min(strs,key=len)

            # So enumerate helps us to iterate with the index and the value, here i will be the index and char will be the value at i.

            # first for loop will iterate over the shortest string characters that is flow.

            # Second for loop will iterate over the elements in strs list. where the if statement inside the for loop will compare the letters
            for i, char in enumerate(shortest_str):
                for other in strs:
                    if other[i] != char:
                     return shortest_str[:i]
                    else:
                        print(other[i])
                        pass
        return shortest_str

Solution1 = Solution()

strs = ["flower","flow","flight"]
print(Solution1.longestCommonPrefix(strs))

strs = ["dog","racecar","car"]
print(Solution1.longestCommonPrefix(strs))
